/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zck.aprioi;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class AprioiZckSampleApp {
    public static void main(String[] args) {
        if(args.length < 1){
            System.err.println("Usage: java AprioiZckSampleApp <path-to-dataset (should be an excel document)>");
            System.err.printf("Current Working Dir: %s", System.getProperty("user.dir"));
            return;
        }
        try {
            File file = new File(args[0]);
            FileInputStream fis = new FileInputStream(file);
            XSSFWorkbook workBook = new XSSFWorkbook(fis);
            XSSFSheet sheet = workBook.getSheetAt(0);

            int _cnt = 0;

            Iterator<Row> itr = sheet.iterator();
            while (itr.hasNext() && _cnt < 10) {
                _cnt++;
                Row row = itr.next();
                Iterator<Cell> itc = row.cellIterator();
                while (itc.hasNext()) {
                    Cell cell = itc.next();
                    switch (cell.getCellType()) {
                    case STRING:
                        System.out.print(cell.getStringCellValue() + "\t");
                        break;
                    case NUMERIC:
                        System.out.print(cell.getNumericCellValue() + "\t");
                        break;
                    case BOOLEAN:
                        System.out.print(cell.getBooleanCellValue() + "\t");
                        break;
                    default:
                        break;
                    }
                }
                System.out.println("");
            }

            workBook.close();
            fis.close();
        } catch (FileNotFoundException fe) {
            fe.printStackTrace();
        } catch (IOException ie) {
            ie.printStackTrace();
        }
    }
}
