/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zck.aprioi;

// import org.junit.Test;
// import static org.junit.Assert.*;

public class AppTest {
    // @Test public void testAppHasAGreeting() {
    //     AprioiZckSampleApp classUnderTest = new AprioiZckSampleApp();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }
}
